// youtube videos for exercises (override GPT videos which are often outdated)

const videoKeys = {
  "Push-Ups": "Eh00_rniF8E",
  Plank: "pvIjsG5Svck",
  Dips: "BjiyWC_cJW0",
  "Bench Press": "4Y2ZdHCOXok",
  Deadlifts: "8np3vKDBJfc",
  "Dumbbell Rows": "roCP6wCXPqo",
  "Diamond Push-Ups": "XtU2VQVuLYs",
  "Decline Push-Ups": "QBlYp-EwHlo",
  "Incline Push-Ups": "Gvm5Q29UHbk",
  "Push-Up with Rotation": "miN74vJbE_w",
  "Pike Push-Ups": "x7_I5SUAd00",
  "Pull-Ups": "eGo4IYlbE5g",
  "Bench Press": "4Y2ZdHCOXok",
  "Push-Ups": "IODxDxX7oi4",
  "Pull-Ups/Chin-Ups": "eGo4IYlbE5g",
  "Bent-Over Rows": "FWJR5Ve8bnQ",
  "Shoulder Press": "rO_iEImwHyo",
  "Lateral Raises": "PzsMitRdI_8",
  "Bicep Curls": "ykJmrZ5v0Oo",
  "Tricep Dips": "6MwtkyNC2ZY",
  "Chest Flyes": "QENKPHhQVi4",
  "Lat Pulldowns": "CAwf7n6Luuc",
  "Dumbbell Bench Press": "X3YrlBmjWrY",
  "Barbell Squats": "S9iWwaqbD3Q",
  Squats: "U3HlEF_E9fo",
  Deadlifts: "op9kVnSso6Q",
  Lunges: "3XDriUn0udo",
  "Leg Press": "qCR9bN3G1t4",
  "Calf Raises": "eMTy3qylqnE",
  "Leg Curls": "Wy1SwoY2aaQ",
  "Romanian Deadlifts": "_oyxCn2iSjU",
  "Step-Ups": "9ZknEYboBOQ",
  "Glute Bridges": "8bbE64NuDTU",
  "Box Jumps": "YLPQsdRDmB0",
  Planks: "ASdvN_XEl_c",
  "Russian Twists": "9V9csctSKj0",
  Crunches: "Xyd_fa5zoEU",
  "Bicycle Crunches": "1we3bh9uhqY",
  "Leg Raises": "l4kQd9eWclE",
  Woodchoppers: "pAplQXk3dkU",
  "Dead Bugs": "MCVX9wRd_h0",
  "Mountain Climbers": "nmwgirgXLYM",
  "Superman Exercise": "z6PJMT2y8GQ",
  "Side Planks": "NQsqPcarPXY",
  Running: "zSIDRHUWlVo",
  Cycling: "r8Qv9to8-bA",
  Swimming: "AQy_c30lNjI",
  "Jump Rope": "aFoektJK9dU",
  "Stair Climbing": "xSB39wbMz4w",
  Rowing: "w2hGNM4l5so",
  "Elliptical Machine": "sHMemwz_HPU",
  "High-Intensity Interval Training (HIIT)": "v=O6olj0O3h4w",
  Boxing: "7CZ5I-PZjEg",
  Burpees: "qLBImHhCXSw&t=50s",
  "Pull-Ups/Chin-Ups": "eGo4IYlbE5g",
  "Bent-Over Rows": "FWJR5Ve8bnQ",
  "Lat Pulldowns": "CAwf7n6Luuc",
  Deadlifts: "op9kVnSso6Q",
  "Leg Curls": "Wy1SwoY2aaQ",
  "Romanian Deadlifts": "_oyxCn2iSjU",
  "Glute Bridges": "8bbE64NuDTU",
  "Box Jumps": "YLPQsdRDmB0",
  "Russian Twists": "9V9csctSKj0",
  Woodchoppers: "pAplQXk3dkU",
  "Bench Press": "4Y2ZdHCOXok",
  "Push-Ups": "IODxDxX7oi4",
  "Shoulder Press": "rO_iEImwHyo",
  "Lateral Raises": "PzsMitRdI_8",
  "Bicep Curls": "ykJmrZ5v0Oo",
  "Tricep Dips": "6MwtkyNC2ZY",
  "Chest Flyes": "QENKPHhQVi4",
  Squats: "U3HlEF_E9fo",
  "Leg Press": "qCR9bN3G1t4",
  "Step-Ups": "9ZknEYboBOQ",
  "Bicep Curls": "ykJmrZ5v0Oo",
  "Chin-Ups": "_71FpEaq-fQ",
  "Hammer Curls": "zC3nLlEvin4",
  "Preacher Curls": "fIWP-FRFNU0",
  "Incline Dumbbell Curls": "soxrZlIl35U",
  "Tricep Dips": "6MwtkyNC2ZY",
  "Close-Grip Bench Press": "wxVRe9pmJdk",
  "Tricep Pushdowns": "GCa8Q4e7laU",
  "Overhead Tricep Extension": "_gsUck-7M74",
  "Skull Crushers": "d_KZxkY_0cM&t=17s",
  "Shoulder Press": "rO_iEImwHyo",
  "Lateral Raises": "PzsMitRdI_8",
  "Front Raises": "gzDawZwDC6Y",
  "Arnold Press": "3ml7BH7mNwQ",
  "Face Pulls": "ljgqer1ZpXg",
  "Bench Press": "4Y2ZdHCOXok",
  "Push-Ups": "IODxDxX7oi4",
  "Chest Flyes": "QENKPHhQVi4",
  "Dumbbell Pullover": "FK4rHfWKEac",
  "Incline Bench Press": "SrqOu55lrYU",
  "Pull-Ups/Chin-Ups": "eGo4IYlbE5g",
  "Bent-Over Rows": "FWJR5Ve8bnQ",
  "Lat Pulldowns": "CAwf7n6Luuc",
  Deadlifts: "op9kVnSso6Q",
  "Seated Cable Rows": "UCXxvVItLoM",
  Planks: "ASdvN_XEl_c",
  "Russian Twists": "9V9csctSKj0",
  Crunches: "Xyd_fa5zoEU",
  "Bicycle Crunches": "1we3bh9uhqY",
  "Leg Raises": "l4kQd9eWclE",
  Squats: "U3HlEF_E9fo",
  Lunges: "3XDriUn0udo",
  "Leg Press": "qCR9bN3G1t4",
  "Calf Raises": "eMTy3qylqnE",
  "Leg Curls": "Wy1SwoY2aaQ",
  "Barbell Rows": "FWJR5Ve8bnQ",
  "Reverse Crunches": "hyv14e2QDq0&t=105s",
  "Dead Hangs": "3CEmHJXbNpc",
  "Jumping Jacks": "iSSAk4XCsRA",
  "Dumbbell Rows": "gfUg6qWohTk",
  "Reverse Lunges": "u_zSfK5ZFU4",
  "Hip Thrusts": "xDmFkJxPzeM",
  "Jump Squats": "A-cFYWvaHr0",
  "Superman Exercise": "z6PJMT2y8GQ",
  "Bicycle Crunches": "1we3bh9uhqY",
  "Reverse Crunches": "hyv14e2QDq0&t=105s",
  "Tuck Jumps": "r7oBejx1PHM",
  "Plank Jacks": "8Do3ssZ23Mc",
  Burpees: "qLBImHhCXSw&t=50s",
  "Hollow Body Hold": "BQCdzRPE9Ao",
  "V-Ups": "iP2fjvG0g3w",
  "Side Plank": "NQsqPcarPXY",
  "Flutter Kicks": "ANVdMDaYRts",
  "Scissor Kicks": "WoNCIBVLbgY",
  "Bodyweight Squats": "xqvCmoLULNY",
  "Pull-Ups": "eGo4IYlbE5g",
  "Dumbbell Shoulder Press": "rO_iEImwHyo",
  "Dumbbell Squats": "v_c67Omje48",
  "Dumbbell Flys": "QENKPHhQVi4",
  "Dumbbell Flyes": "QENKPHhQVi4",
  "Dumbbell Lunges": "D7KaRcUTQeE",
  "Flutter Kicks": "ANVdMDaYRts",
  "Side Plank": "NQsqPcarPXY",
  Rows: "FWJR5Ve8bnQ",
  Dips: "2z8JmcrW-As",
  "Tricep Extensions": "_gsUck-7M74",
  "Bent Over Rows": "FWJR5Ve8bnQ",
  "Single Arm Dumbbell Rows": "dFzUjzfih7k",
  "Tricep Kickbacks": "6SS6K3lAwZ8",
  "Close Grip Bench Press": "wxVRe9pmJdk",
};

export default videoKeys;
